---

#This playbook upgrades an existing cluster to a newer version of k3s. The version number is specified in the group_vars/all.yaml file

- name: Upgrade K3S on all nodes
  hosts: kubernetes_master:kubernetes_worker
  roles:
    - upgrade_k3s
  tags:
    - k3s_setup_upgrade_cluster
  become: true